image: node

pages:
  script:
    - npm install --force
    - npm run build && npm run export
    - rm -rf public/
    - mkdir -p public/
    - mv out/* public/.
    - mv out/.* public/.
  artifacts:
    paths:
      - public
  only:
    - main