stages:
  - deploy

cache:
  paths:
    - $CI_PROJECT_DIR/.pub-cache/

before_script:
  - flutter config --enable-web
  - flutter pub get
  - export PUB_CACHE=$CI_PROJECT_DIR/.pub-cache
  - export PATH="$PATH":"$PUB_CACHE/bin"

pages:
  stage: deploy
  image: "cirrusci/flutter:latest"
  script:
    - flutter build web --web-renderer html
    - rm -rf build/web/canvaskit
    - cp -r build/web public
    - ls public
  artifacts:
    paths:
      - public
  only:
    - main
