image: node

before_script:
    - npm install

cache:
    paths:
        - node_modules

pages:
    before_script:
        # Clean public folder
        - find public -mindepth 1 -maxdepth 1 -type d | xargs rm -rf
        - find public -type f -name "*.html" | xargs rm -rf
    script:
        # Build application and move content to public folder
        - npm run build && npm run export # Eq. to 'next build && next export'
        - mv out/* public
    after_script:
        # Cleanup
        - rm -rf out
    artifacts:
        paths:
            - public
    only:
        - main
