image: node

before_script:
    - npm install

pages:
    script:
        - npm run build && npm run export
        - mv out public
    artifacts:
        paths:
            - public
    only:
        - main
