image: node

before_script:
    - npm install

cache:
    paths:
        - node_modules

pages:
    script:
        - npm run export
        - mv out/* public
        - rm -rf out
    artifacts:
        paths:
            - public
    only:
        - main
