image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - .next/cache/

pages:
  before_script:
    - rm -rf public
  script:
    - npm run-script build && npm run-script export
    - mv out/* public
  after_script:
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - main