name: igem
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.4
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
 
  fonts:
     - family: DrukWide
       fonts:
         - asset: fonts/DrukWide-Bold-Trial.otf
     - family: Rockabye
       fonts:
         - asset: fonts/RockabyeRegular-K7Zqy.otf
  