image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - npm run build && npm run export
    - rm -rf public/*
    - ls
    - mv out/* public
    - ls
  after_script:
    - rm -rf out
    - ls
  artifacts:
    paths:
      - public
  only:
    - main